### ISSUE TITLE
Issue with login to hass.io after login in to panel.

### ISSUE THREAD

**Issue by bandric1** [hassio-addons/addon-home-panel#10]
# Problem/Motivation
Issue when trying to sign in after redirect to Hass.io
> (Why the issue was filed)
< When i tried to login to panel via Ipad2 the last ios posible it redirects me to hass.io login but from there i cannot login to my account. Hass.io works on this ipad normaly i can login from the same browser and everything
## Expected behavior
< To be able to login to hassio after i succesfuly login in to panel.
> (What you expected to happen)

## Actual behavior
it says trying to connect to hassio and fails
> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by il-bert** [comment]
same problem

**Comment by LoneWolf345** [comment]
ditto

**Comment by timmo001** [comment]
I will merge this and the other issue opened into the upstream since they should hopefully be fixed when the API is rewritten.

https://github.com/timmo001/home-panel/issues/233
