### ISSUE TITLE
Media Player Card?

### ISSUE THREAD

**Issue by astone123** [hassio-addons/addon-home-panel#15]
## Proposed changes

Do any contributors know how to go about creating a media player card for the Home Panel add-on? I'd like to be able to configure the Home Panel add-on to display media player status and controls. 

I'd be happy to work on this change myself eventually, but I'm not yet familiar with how Hassio Add-ons are built. At this point I'm wondering if anyone involved has thoughts about a media player card for this add-on.

**Comment by timmo001** [comment]
This is possible, just use the standard hass type card. You may want to increase the width and height to show the controls.

FYI: any Home Panel specific issues, please open them here:

https://github.com/timmo001/home-panel/issues/new/choose
