### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by teeodor** [hassio-addons/addon-home-panel#150]
After install in home assistant supervisor on raspberry 32 bit so I can't login.
I login in the first page, after I go in hamburger menu, login home assistant, put my local address, login with my username and password and after I have no user

**Comment by fatzgenfatz** [comment]
When I login with wrong credentials I get the Home-Assistant error page, when I login with correct credentials I get a otherwise blank html-page with 401: Unauthorized
Home-Assistant haos_generic-x86-64-6.6 in a VM running on a Synology DS.

**Comment by adamhorsburgh** [comment]
I'm having the same issue. Raspberry Pi 4 running HAOS. I also get the 401:  Unauthorized error
