### ISSUE TITLE
Can't create user under certain circumstances

### ISSUE THREAD

**Issue by mbrownnycnyc** [hassio-addons/addon-home-panel#16]
# Problem/Motivation

Receiving the following error when creating a new user after installation:

     Error: 404 - {"name":"NotFound","message":"Page not found","code":404,"className":"not-found","data":{"url":"/login/setup"},"errors":{}}

## Expected behavior

Create a user

## Actual behavior

Does not create a user.

## Steps to reproduce

I had upgraded, then faced a similar issue when logging in with an existing user.
I then uninstall (couldn't find the `config.json` file, where is it?), and reinstalled.
Then faced this reported issue
Enter user name and password on http://hassio.local:8234/
Click "Sign up"

## Proposed changes

This may help: https://github.com/feathersjs/docs/issues/1220

**Comment by timmo001** [comment]
Does this still occur for you in the later releases?

> I then uninstall (couldn't find the `config.json` file, where is it?), and reinstalled.
> Then faced this reported issue

This is no longer the way the app works. Please read the release notes for Home Panel v0.8.0

https://github.com/timmo001/home-panel/releases/tag/v0.8.0
