### ISSUE TITLE
Getting an old version of Home Panel

### ISSUE THREAD

**Issue by MrSaatci** [hassio-addons/addon-home-panel#173]
# Problem/Motivation

I noticed that on the dev repo the latest version is 2.11, we're running 2.4 on Hassio and it's just unusable.

## Expected behavior

being functional

## Actual behavior

one is not even able to save any changes or config.

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes
Upgrade the addon to reflect the latest release

**Comment by frenck** [comment]
The add-on version is 2.4 (which is the latest), it runs Home Panel 2.11.6, see:

<https://github.com/hassio-addons/addon-home-panel/blob/main/home-panel/Dockerfile#L24>

This is also listed in things like: Release notes. Which are shipped with the add-on and viewable here on GitHub too.

>  it's just unusable

Sorry to hear that.

> on Hassio

The term "Hassio" has been dropped years ago, it's ambiguous and can have a lot of different meanings. You should avoid using it.
