### ISSUE TITLE
 Logging to HA from Home Panel doesn't work?

### ISSUE THREAD

**Issue by Krzysztonek** [hassio-addons/addon-home-panel#176]
Hi,

I faced an issue when trying to login to HA from Home Panel:

![image](https://user-images.githubusercontent.com/87784133/174681100-8639456d-70a7-452d-8948-f24dd337cd13.png)

All the time I see this `Home Assistant not connected` message on the Group Card (on the right)
When clicking [**_Log in to HA_**] button, the screen is just refreshing several times and finally, I'm landing at the same, initial point. 

As the result, I'm not able to display any HA entities on Home Panel, which becomes useless at this moment..
 
I checked Home Panel configuration and its logs: 
![image](https://user-images.githubusercontent.com/87784133/174681975-137d0afe-2d57-4f1d-b85e-41d2a927c9ce.png)
however, no issues were found.
 
Maybe there is something missing in my setup/config but I found nothing relevant in the add-on documentation.
May I count on any support?

**Comment by frenck** [comment]
@timmo001 Is this something you are familiar with?

**Comment by Krzysztonek** [comment]
Yes, @frenck, I've read the whole Home Panel documentation available from [@timmo001](https://github.com/timmo001), however, I haven't found any hints which might help me find the answer to resolve my problem with logging to HA instance from Home Panel. This integration looks strange to me and it's not so obvious. Maybe it is so complex for the newbies.

**Comment by EagleWolfpack** [comment]
Hi!
I've the same problem
Home Panel does not store the config.
It's also not possible to change the colors...
On selecting a different color, nothing happens.

Kind Regards
Chris
