### ISSUE TITLE
Unable to configure News API

### ISSUE THREAD

**Issue by miguelcouteirorodrigues** [hassio-addons/addon-home-panel#177]
# Problem/Motivation

> Setting the NEws API key in settings does not seem to properly work.

## Expected behavior

> News feed card would be configurable.

## Actual behavior

> News feed card complains that API key has not been set.

## Steps to reproduce

> Set News API key in configuration.
Switch to overview panel.
Create a news feed card.
"News configuration" section shows message "Invalid config or you do not have a News API key set in your config." under Source field.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

For further detail, exporting the configuration backup shows that the key has been properly set under a "news" entry. However, moving away from the Configuration screen and back causes it to not be shown (option is shown as being empty.
Logging as debug shows no error message.

Seems as though it is being saved to one value and read from another, perhaps?

**Comment by jocamacedo** [comment]
I am having the exact same problem.  If anyone has a fix, I would love to hear about it.  Thanks.

**Comment by djp8djp** [comment]
Same her. Configuration page takes my news feed API key (from NewsAPI), but that does not seem to be taken up by card, which complains : Invalid config or you do not have a News...

**Comment by jocamacedo** [comment]
I have tried a number of times but the issue remains.  The add on is up to date.  How can we resolve this?  Thanks!

**Comment by republicandaddy** [comment]
I am also having the same issue.  The News API part would be a FANTASTIC addition if it worked.  I've poked around a bit thinking maybe there was a config file that needed to be modified, but I don't see anything.  

Please help.

**Comment by antimidas** [comment]
This feature does NOT work.
