### ISSUE TITLE
Home Panel: no access outside of Home Assistant

### ISSUE THREAD

**Issue by sirBlackat** [hassio-addons/addon-home-panel#179]
Did not find the way to access to Home Panel directly from any browser in my network, can see/run/configure Home Panel as the internal part of Hass but not direcly.

There is my trace log:

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: Home Panel
 A web frontend for controlling the home
-----------------------------------------------------------
 Add-on version: 2.5.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.2  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2022.10.3
 Home Assistant Supervisor: 2022.10.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
Log level is set to TRACE
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/nginx.sh
[19:37:28] TRACE: bashio::addon.port 80
[19:37:28] TRACE: bashio::addons self addons.self.network.80-tcp .network["80/tcp"] // empty
[19:37:28] TRACE: bashio::cache.exists: addons.self.network.80-tcp
[19:37:28] TRACE: bashio::fs.file_exists: /tmp/.bashio/addons.self.network.80-tcp.cache
[19:37:28] TRACE: bashio::var.false: self
[19:37:28] TRACE: bashio::cache.exists: addons.self.info
[19:37:28] TRACE: bashio::fs.file_exists: /tmp/.bashio/addons.self.info.cache
[19:37:28] TRACE: bashio::cache.get: addons.self.info
[19:37:28] TRACE: bashio::cache.exists: addons.self.info
[19:37:28] TRACE: bashio::fs.file_exists: /tmp/.bashio/addons.self.info.cache
[19:37:28] TRACE: bashio::var.has_value: .network["80/tcp"] // empty
[19:37:28] TRACE: bashio::jq: {"name":"Home Panel","slug":"a0d7b954_home-panel","hostname":"a0d7b954-home-panel","dns":["a0d7b954-home-panel.local.hass.io"],"description":"A web frontend for controlling the home","long_description":"# Home Assistant Community Add-on: Home Panel
[![Release][release-shield]][release] ![Project Stage][project-stage-shield] ![Project Maintenance][maintenance-shield]
[![Discord][discord-shield]][discord] [![Community Forum][forum-shield]][forum]
[![Buy me a coffee][buymeacoffee-shield]][buymeacoffee]
A web frontend for controlling the home. Integrates with
 [Home Assistant][hass] as an alternative / additional frontend. Uses a
 customisable and themeable card based UI which can be used on a touch screen.
![banner][banner]
## Screenshots
![Main Screen Screenshot][screen-main]
![Configuration Screenshot][screen-configuration-main]
![Showcase Purple Space][showcase-purple-space]
[banner]: https://raw.githubusercontent.com/timmo001/home-panel/master/documentation/resources/banner.png
[buymeacoffee-shield]: https://www.buymeacoffee.com/assets/img/guidelines/download-assets-sm-2.svg
[buymeacoffee]: https://www.buymeacoffee.com/timmo
[discord-shield]: https://img.shields.io/discord/478094546522079232.svg
[discord]: https://discord.me/hassioaddons
[forum-shield]: https://img.shields.io/badge/community-forum-brightgreen.svg
[forum]: https://community.home-assistant.io/t/home-panel-a-touch-compatible-webapp-for-controlling-the-home/62597?u=timmo001
[hass]: https://www.home-assistant.io/
[home-panel]: https://github.com/timmo001/home-panel
[maintenance-shield]: https://img.shields.io/maintenance/yes/2022.svg
[project-stage-shield]: https://img.shields.io/badge/project%20stage-production%20ready-brightgreen.svg
[release-shield]: https://img.shields.io/badge/version-v2.5.0-blue.svg
[release]: https://github.com/hassio-addons/addon-home-panel/tree/v2.5.0
[screen-configuration-main]: https://raw.githubusercontent.com/timmo001/home-panel/master/documentation/resources/screen-configuration-main.png
[screen-main]: https://raw.githubusercontent.com/timmo001/home-panel/master/documentation/resources/screen-main.png
[showcase-purple-space]: https://raw.githubusercontent.com/timmo001/home-panel/master/documentation/docs/showcase/timmo/purple-space.png","advanced":false,"stage":"stable","repository":"a0d7b954","version_latest":"2.5.0","protected":true,"rating":8,"boot":"auto","options":{"certfile":"fullchain.pem","keyfile":"privkey.pem","ssl":true,"log_level":"trace"},"schema":[{"name":"certfile","required":true,"type":"string"},{"name":"keyfile","required":true,"type":"string"},{"name":"log_level","optional":true,"type":"select","options":["trace","debug","info","notice","warning","error","fatal"]},{"name":"ssl","required":true,"type":"boolean"}],"arch":["aarch64","amd64","armhf","armv7","i386"],"machine":[],"homeassistant":null,"url":"https://github.com/hassio-addons/addon-home-panel","detached":false,"available":true,"build":false,"network":{"80/tcp":null},"network_description":{"80/tcp":"Web UI (Not required for Ingress)"},"host_network":false,"host_pid":false,"host_ipc":false,"host_dbus":false,"privileged":[],"full_access":false,"apparmor":"default","icon":true,"logo":true,"changelog":true,"documentation":true,"stdin":false,"hassio_api":false,"hassio_role":"default","auth_api":false,"homeassistant_api":false,"gpio":false,"usb":false,"uart":false,"kernel_modules":false,"devicetree":false,"udev":false,"docker_api":false,"video":false,"audio":false,"startup":"application","services":[],"discovery":[],"translations":{"en":{"configuration":{"log_level":{"name":"Log level","description":"Controls the level of log details the add-on provides."},"ssl":{"name":"SSL","description":"Enables/Disables SSL (HTTPS) on the web interface."},"certfile":{"name":"Certificate file","description":"The certificate file to use for SSL. Note that this file must exist in the /ssl/ folder."},"keyfile":{"name":"Private key file","description":"The private key file to use for SSL. Note that this file must exist in the /ssl/ folder."}},"network":{"80/tcp":"Web interface (Not required for Ingress)"}}},"ingress":true,"signed":true,"state":"started","webui":null,"ingress_entry":"/api/hassio_ingress/AbIS2w15wjFBDb_Es2tWFh4hRDLN4UlQwT-CT0Fx-VM","ingress_url":"/api/hassio_ingress/AbIS2w15wjFBDb_Es2tWFh4hRDLN4UlQwT-CT0Fx-VM/","ingress_port":8099,"ingress_panel":true,"audio_input":null,"audio_output":null,"auto_update":false,"ip_address":"172.30.33.2","version":"2.5.0","update_available":false,"watchdog":true,"devices":[]} .network["80/tcp"] // empty
[19:37:28] TRACE: bashio::cache.set: addons.self.network.80-tcp 
[19:37:28] TRACE: bashio::fs.directory_exists: /tmp/.bashio
[19:37:28] TRACE: bashio::var.has_value: 
cont-init: info: /etc/cont-init.d/nginx.sh exited 0
cont-init: info: running /etc/cont-init.d/secrets.sh
[19:37:28] TRACE: bashio::fs.file_exists: /data/secret.txt
[19:37:28] INFO: Update secret in config
[19:37:28] INFO: Update database path in config
cont-init: info: /etc/cont-init.d/secrets.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun home-panel (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
s6-rc: info: service legacy-services successfully started
[19:37:29] TRACE: bashio::net.wait_for 8234
[19:37:29] INFO: Run Home Panel...
yarn run v1.22.19
$ node lib/
info: API started
[19:37:33] INFO: Starting NGINX...

**Comment by tjorim** [comment]
Did you set a network port in the add-on configuration?

**Comment by sirBlackat** [comment]
no, did not find the option in documentation, saw it only in docker style installations but I have HAss OS

**Comment by tjorim** [comment]
Check again, it's a very big button:
![Screenshot_20221012-215027~2.png](https://user-images.githubusercontent.com/1294876/195434912-945e7326-a3bb-4c51-89b9-aa7e446d491f.png)

**Comment by sirBlackat** [comment]
OK, sorry I didn't realize that such a thing would be labeled "show disabled ports"
