### ISSUE TITLE
Automation: On click action

### ISSUE THREAD

**Issue by psoemmer** [hassio-addons/addon-home-panel#20]
# Problem/Motivation

> Need to switch automations on/off in Home Panel

## Expected behavior

> On click action of an automation widget: toggle on/off

## Actual behavior

> On click action of an automation widget: nothing?

## Steps to reproduce

> add an automation to home panel an try to switch the state

## Proposed changes

> Change the action of the widget

**Comment by timmo001** [comment]
Please open an issue in the upstream repository. Thanks

https://github.com/timmo001/home-panel/issues
