### ISSUE TITLE
Socket connection timed out

### ISSUE THREAD

**Issue by Giancky79** [hassio-addons/addon-home-panel#21]
# Problem/Motivation
hassio 0.92.2, with home panel addon 0.4.1, Socket connection timed out
> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce
new installation
> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by fets13** [comment]
Giancky79
did you set ssl ?
In my case, it inly works with ssl off

**Comment by Giancky79** [comment]
i'm try portforwarding and not working, with ssl and without, same problem

**Comment by Giancky79** [comment]
i have found solution, because virtualize home assistant, when i'm out of home, i have the websocket error

**Comment by Giancky79** [comment]
Ok, with my ip working, with my address of homeassistant:8123, error message, with or without ssl

**Comment by cherokee93** [comment]
Same Issue here, just can't log in.

SSL on/SSL off/local ip/public ip/https/http/from lan/from outside
I only get Socket connection timed out on my hassio instance using Hassio Ingress.

This project looks amazing!

**Comment by dyennam** [comment]
Same issue, doesn't work with ssl off. Get an "Authentication timed out" error message. This is on a new installation. I am not even able to see any logs also.
My Config:
{
  "ssl": false,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "log_level": "debug"
}

**Comment by cherokee93** [comment]
> Same issue, doesn't work with ssl off. Get an "Authentication timed out" error message. This is on a new installation. I am not even able to see any logs also.
> My Config:
> {
> "ssl": false,
> "certfile": "fullchain.pem",
> "keyfile": "privkey.pem",
> "log_level": "debug"
> }

For me it started to work without Ingress (disabling **show in sidebar** and setting up the web ui port) using my external IP

**Comment by Giancky79** [comment]
no solution for this problem, or this addon is coming deprecated?

**Comment by timmo001** [comment]
Ingress is only supported for the frontend. If you are accessing the app remotely, please add a port to the app's config and access home panel like you did previously.

Ingress will only work when you use the same address/ip to access home assistant. i.e. the app will not work with remote access to ha when ingress is used.

**Comment by cherokee93** [comment]
> Ingress is only supported for the frontend. If you are accessing the app remotely, please add a port to the add-on's config and access home panel like you did previously.
> 
> Ingress will only work when you use the same address/ip to access home assistant. i.e. the app will not work with remote access to ha when ingress is used.

Yeah ok. Still not working on my end. 
Even using the pc in my lan, [if I use the local machine ip it doesn't work.
](https://user-images.githubusercontent.com/12370126/58818161-b5027c00-862d-11e9-9d6a-17aa1567d076.png)
It only works using the custom port mapping (no ingress) with my public ip

**Comment by timmo001** [comment]
> It only works using the custom port mapping (no ingress) with my public ip

That's what I said.

**Comment by Giancky79** [comment]
Perfect, why with 4.1 ingress option?

**Comment by sewashburn** [comment]
Same error message for me.  How can I tell if it is really creating a user?  I get the Socket Error Timed Out message when I click on LOGIN.  Are we supposed to be using port 3234 or 8234?  I have found conflicting information.  I would love to be able to use Home Panel on my Amazon Kindle Fire 8.9.

**Comment by Sandteufel** [comment]
Well, as for my installation (ubuntu, docker, ssl) not working. I receive two types of errors or invalid login, or Authentication timed out...

some logs for 1 type of error:
`[30/Jun/2019:00:21:43 +0300] 304 -(192.168.1.99) GET /service-worker.js HTTP/2.0 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.2 Safari/605.1.15)
error: NotAuthenticated: Invalid login
    at new NotAuthenticated (/opt/api/node_modules/@feathersjs/errors/lib/index.js:93:17)
    at app.authenticate.then (/opt/api/node_modules/@feathersjs/authentication/lib/hooks/authenticate.js:87:31)`

**Comment by siege801** [comment]
Any progress on this? I'm having the same issue. I've tried about every combination of ssl/non-ssl, local ip, duckdns methods of connecting that I can think of. I get the same "Socket connection timed out" error.  I'm fairly desperate to get home-panel working because the old iPad I want to use as a wall panel doesn't work with Lovelace.

**Comment by cherokee93** [comment]
> Any progress on this? I'm having the same issue. I've tried about every combination of ssl/non-ssl, local ip, duckdns methods of connecting that I can think of. I get the same "Socket connection timed out" error. I'm fairly desperate to get home-panel working because the old iPad I want to use as a wall panel doesn't work with Lovelace.

Not fixed on my end as well, the only thing you need to try is to port forward the ip and not use it with local ip/ingress. Then it works (at least for me it worked but this kinda sucked and i'm not using it anymore)

**Comment by rafdalb** [comment]
I cannot make it working as well, honestly documentation is not clear, I don't really understand how home-panel talks with homeassist. In my case I'm using hass.io without SSL, exposed via another nginx (my own) on port 443 which does L7 routing to different servers depending on hostname. 

In this case I don't even know which address/port I've to use in this case.  Would be good if somebody explain how it works.
