### ISSUE TITLE
Getting home screen

### ISSUE THREAD

**Issue by gdc2john** [hassio-addons/addon-home-panel#22]
Hi There.

I have installed Home Panel on Hasios, all installed correctly, config save as non ssl.
I can get to the url http:// myhassip:3234 and get: “Home Panel API is active!. This is the correct location for the API of Home Panel. Use this to test that the backend is active.
This is not the main application. Please check the docs if you do not know how to access this.”

I can log onto Home Panel from within home assistant only.

Well for the life of me I cant find anywhere in the documentation how to get to the logon screen from the browser IP address.
Any help would be appreciated.
Thanks John

**Comment by roelv30** [comment]
Hi John,

Had the same problem, solved it by doing the following: go to the settings page of the home screen addon. Scroll to the bottom where you see the network option, (by default the 80/tcp input says disabled). Put a port number here (can be random if it doesn't interfere with another number on your server) for instance 2315. Press save and restart the addon. After the restart you can navigate with your browser to http://myhassip:2315 and you should see the login screen.
Hope this helps.

**Comment by gdc2john** [comment]
Excellent, worked a treat, pity this information isn't in the instructions.
Thanks for your help, appreciated 
John
