### ISSUE TITLE
Enhancement: MQTT API (i.e. change menu page upon receiving a MQTT topic)

### ISSUE THREAD

**Issue by PieBru** [hassio-addons/addon-home-panel#23]
Hi,

I'm just exploring Home Panel and it seems to me the best "family HA interface" around. The HA native UI is too technical for my family members.

IMO it would be nice if the "family" panel could "live" by reacting to MQTT (or other standard) messages, i.e.:
- show the weather page whan a thunderstorm is nearby, thanks to my DIY franklin outdoor sensor;
- show the page with main entrance ESP32 CAM stream when someone rings the IoT doorbell;
- show the page with MotionEye surveillance dash when external sensors wake up for a presence - or a jamming ;) or other alarming events;
- show the environment page when temperature/humidity/particles/gasses are at abnormal level;
... and so on ...

Is it possible now or can it be planned?
If not, can you suggest a way I can achieve this goal in a relatively simple way?

Thanks,
Piero

**Comment by PieBru** [comment]
Bump, sorry.
Is it already possible?
Thanks,
Piero



Il mer 11 set 2019, 13:18 addons-assistant[bot] <notifications@github.com>
ha scritto:

**Comment by timmo001** [comment]
The upstream repository is where you should post any app-specific issues or feature requests.

This is available via the api `controller` endpoint. There is a HA integration awaiting approval/review also.
