### ISSUE TITLE
Link to Configuration Documents is broken

### ISSUE THREAD

**Issue by restauffer** [hassio-addons/addon-home-panel#232]
# Problem/Motivation

Cannot get to configuration instructions.
## Expected behavior>
 When clicking on the link 

https://github.com/hassio-addons/addon-home-panel/blob/main/home-panel/DOCS.md

on point 9 (Please see [here](https://home-panel-docs.timmo.dev/configui/) for how to configure Home Panel.) it is expected you ill be taken to the documents.

## Actual behavior
The link is broken. You get a "Page Not Found" error

## Steps to reproduce
Go to:
https://github.com/hassio-addons/addon-home-panel/blob/main/home-panel/DOCS.md

Click on the word "here" in point 9

## Proposed changes
Fix the link

**Comment by restauffer** [comment]
Ping

**Comment by restauffer** [comment]
Looks like this add-on has been abandoned!!

**Comment by rvalitov** [comment]
Exactly, this issue has already been reported and closed automatically without any fix or comments #212

**Comment by frenck** [comment]
The upstream project is no longer being maintained. The last release was 2 years ago.

We've decided to stop updating/shipping this add-on.

Sorry!

../Frenck
