### ISSUE TITLE
No access to port 8234

### ISSUE THREAD

**Issue by rafdalb** [hassio-addons/addon-home-panel#28]
# Problem/Motivation

Home panel not working as access to 8234 is not available.

## Expected behavior

I would expected to have direct access to port 8234 but there is no server listening on this port (am I wrong on something?)

## Steps to reproduce

Installed home-panel from hass.io, started with both default config (ssl=true) and without ssl. Same behavior.

Output from hass.io:

logs

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: Home Panel
 A touch-compatible web frontend for controlling the home
-----------------------------------------------------------
 Add-on version: 0.5.0
 You are running the latest version of this add-on.
 System: HassOS 2.12  (amd64 / qemux86-64)
 Home Assistant version: 0.96.5
 Supervisor version: 170
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] secrets.sh: executing... 
[cont-init.d] secrets.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[12:43:15] INFO: Run API..
[services.d] done.
SSL (HTTPS) is not active!!!
info: API started on http://localhost:3234
[12:43:16] INFO: Starting NGINX...

What is the way to access to home-panel? Any specific link? Something else? I'm using an external nginx as ingress controller for my environment which doesn't have homeassistant only.

Thanks.

**Comment by rafdalb** [comment]
My hass.io runs on a vm in proxmox so cannot really take text of docker ps. What I can tell you is that I don't see any docker listening on port 8234, only one on port 3234 which is the API one, which is actually answering also to http requests.

**Comment by rdalbenzio** [comment]
Looks like uninstalling and reinstalling home-panel solved the issue. I upgraded from 0.4.5 to 0.5 and it didn't work. Uninstalling and reinstalling made the trick.

Thanks.

**Comment by rafdalb** [comment]
Looks like uninstalling and reinstalling home-panel solved the issue. I upgraded from 0.4.5 to 0.5 and it didn't work. Uninstalling and reinstalling made the trick.

Thanks.
