### ISSUE TITLE
Breaks when changing hassio hostname

### ISSUE THREAD

**Issue by jimmyeao** [hassio-addons/addon-home-panel#29]
# Problem/Motivation

> After changing the hostname of Hass.io to a vanity name, unable to log in to home assistant (it tries to go to haasio)
`http://hassio:8123/auth/authorize?response_type=code&client_id=http%3A%2F%2F192.168.0.146%3A8234%2F&redirect_uri=http%3A%2F%2F192.168.0.146%3A8234%2F%3Fauth_callback%3D1&state=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`

## Expected behavior

> It should read the hotname and allow me to log in
## Actual behavior

> recieved error it couldnt connect to hassio

## Steps to reproduce

> use hass.io/system to change hostname

## Proposed changes

update plugin to read hostname as a variable and use that

**Comment by timmo001** [comment]
The app has been updated to the new major version of Home Panel. Please upgrade and try again. Reopen if your issue is still unresolved.
