### ISSUE TITLE
Error creating user

### ISSUE THREAD

**Issue by JSanchezFDZ** [hassio-addons/addon-home-panel#30]
# Problem/Motivation

> When installing the addon everything is correct.
> The problem is when you run it, the interface opens but I can't create a user.

![Error in addon](https://user-images.githubusercontent.com/17337482/64428721-ba4fe680-d0b4-11e9-9514-70a34a1f392c.png)

## Expected behavior

> Create first user

## Actual behavior

> I can't access home panel with user.

## Steps to reproduce

Raspberry Pi 3 b+
Hass.io + HA

> Install Home Panel
> Open ports in router
> Open UI Home Panel
> Create user
> URL = URL OF MY DUCKDNS

## Proposed changes

> Create the first user automatically and fix this error.

Sorry for my bad english.

**Comment by timmo001** [comment]
The app has been updated to the new major version of Home Panel. Please upgrade and try again. Reopen if your issue is still unresolved.
