### ISSUE TITLE
Panel / Config not stored --> USER AND Dashboard deleted after restart of Addon

### ISSUE THREAD

**Issue by thundergreen** [hassio-addons/addon-home-panel#31]
# Problem/Motivation
When restarting hassIO or just this the addon All data is lost. Dashboard and user as well.

> (Why the issue was filed)

## Expected behavior
Saving user and dashboard :)

> (What you expected to happen)

## Actual behavior
After each restart off addon (hassio) user and dashboard are deleted
> (What actually happened)

## Steps to reproduce
1. start addon
2. Create user
3. create dashboard
4. save changes
5. restart
6. see and cry! All data lost
> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by timmo001** [comment]
On it now. Thanks for reporting!

**Comment by timmo001** [comment]
Fixed! Release on its way
