### ISSUE TITLE
Error When Starting Home Panel After Upgrade to 1.0.2

### ISSUE THREAD

**Issue by chipriley** [hassio-addons/addon-home-panel#32]
# Problem/Motivation

> After updating to the most recent release (1.0.2) and attempting to start the add-on (stock config on Hass.io), an error occurs with secrets.sh and everything TERMs.

## Expected behavior

> HP start up and I go to the web UI to start configuration.

## Actual behavior

> The following happens in the logs:
```
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] secrets.sh: executing... 
sed: bad option in substitution expression
[cont-init.d] secrets.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

## Steps to reproduce

> Update the add-on and start it up.

**Comment by thundergreen** [comment]
Just remove old add-on and reinstall it ..you will lose your data anyway

**Comment by chipriley** [comment]
>Just remove old add-on and reinstall it ..you will lose your data anyway 

@thundergreen just uninstalling/reinstalling the add-on didn’t work. Is there something else residual that needs removal?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by thundergreen** [comment]
Afaik know not . Could you please use debug for the logs and post it?

chipriley <notifications@github.com> schrieb am So., 15. Sep. 2019, 10:45:

**Comment by sinclairpaul** [comment]
@chipriley Could you post the full addon log?
