### ISSUE TITLE
some sensors not available in homepanel

### ISSUE THREAD

**Issue by nocturneop15** [hassio-addons/addon-home-panel#34]
When creating new card in hompanel, I can see all sensors/switches I have in my Homeassistant, except speedtest: 
sensor.speedtest_download
sensor.speedtest_upload
sensor.speedtest-ping

those mentioned above are not available in drop-down menu in card settings. 

HassOS 2.12
Homepanel 1.0.4
Home Assistant 0.98.5

**Comment by timmo001** [comment]
Please post your issue here https://github.com/timmo001/home-panel/issues
