### ISSUE TITLE
I-Frame Height not working v 1.0.4

### ISSUE THREAD

**Issue by thundergreen** [hassio-addons/addon-home-panel#35]
# Problem/Motivation
Adding I-frame widget won't take into account the height given in the widget configuration
> (Why the issue was filed)

## Expected behavior
configurable height for i-frame widget
> (What you expected to happen)

## Actual behavior
height is automaticall chosen. no change possible
> (What actually happened)

## Steps to reproduce
1. create iframe
2. change height
3. see it won'T change the height
> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
Please log it upstream https://github.com/timmo001/home-panel/issues

**Comment by thundergreen** [comment]
What you mean exactly ? Sorry But upstream logging is nw to me.

**Comment by sinclairpaul** [comment]
@thundergreen Please log the application issues/requests in the application repo, not the addon repo, as you have been doing with your feature requests.
