### ISSUE TITLE
Light Brightness also turns off/on light

### ISSUE THREAD

**Issue by Nailik** [hassio-addons/addon-home-panel#36]
# Problem/Motivation

When i change the light brigthness on the tile it turns on or off the light.

Happens on desktop pc with windows and chrome browser, doesn't happen on android phone with chrome browser.

The slider jumps back and forth when i change the brightness happens on desktop and phone.

**Comment by sinclairpaul** [comment]
As its not really an issue with the addon build, could you report your issue at  https://github.com/timmo001/home-panel/issues

Thanks
