### ISSUE TITLE
Tablet show only middle screen buttons

### ISSUE THREAD

**Issue by dustardly** [hassio-addons/addon-home-panel#37]
# Problem/Motivation
Tablet after upgrade home panel to 1.2.1 show only buttons in half screen ,hotizontal superior part is visible, the other half part is black. 

## Expected behavior

> (What you expected to happen)

Fix for right visual , like was for width, I’d like manual input the high visual.

## Steps to reproduce

Use a tablet 8’’ Android 5.0

Working good on previous version

**Comment by timmo001** [comment]
Can you upgrade to the latest version and provide screenshots/logs for your issue.

If your issue is not specific to the add-on, please close this issue and open a new one in the upstream repository.

https://github.com/hassio-addons/addon-home-panel/issues

**Comment by timmo001** [comment]
This issue is outdated and also posted on the wrong repository. You should post the issue on the upstream, after updating if you are still facing this issue.

Thanks
