### ISSUE TITLE
Add-on page images broken

### ISSUE THREAD

**Issue by ivelin** [hassio-addons/addon-home-panel#39]
# Problem/Motivation
Please s
![Screen Shot 2019-10-11 at 5 52 35 PM](https://user-images.githubusercontent.com/2234901/66689470-9ef66f00-ec50-11e9-81f7-5ac2f24bc46d.png)
ee screenshot.
> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by timmo001** [comment]
Thanks for this. I've updated the screenshots on the upstream repository so will need to update this end as well
