### ISSUE TITLE
Charts do no load when connecting from outside of the network

### ISSUE THREAD

**Issue by CervDotBe** [hassio-addons/addon-home-panel#43]
I am afraid this project is abandoned, but I'll try to log another issue and hopefully get an answer.

When connecting from an external connection charts **do not** load on the tiles.
When connecting from inside the local network chart do load on the tiles.

I tried this on different devices and networks.

**Comment by timmo001** [comment]
https://timmo.dev/home-panel/faq/#i-am-using-charts-for-my-entities-but-they-are-not-showing
