### ISSUE TITLE
Tile sizing is wrong with height >= 2

### ISSUE THREAD

**Issue by CervDotBe** [hassio-addons/addon-home-panel#44]
When using tiles which have height 2 or more the sizing is wrong in comparison with 1 height tiles. This gives interface inconsistencies.

Example:
![image](https://user-images.githubusercontent.com/29871395/70983099-73608c80-20b8-11ea-9302-8f45c488a135.png)

**Comment by crus1313** [comment]
True, the 2x should account for the space between 1x tiles and ad that value to itself.
