### ISSUE TITLE
Fully kiosk web browser loses login

### ISSUE THREAD

**Issue by hugodelaroza** [hassio-addons/addon-home-panel#45]
# Problem/Motivation
I use fully kiosk browser to show home panel addon in a tablet. The problem is that's in a day or two it loses the login and I have to login again
> (Why the issue was filed)

## Expected behavior
The login should last forever
> (What you expected to happen)

## Actual behavior
Lose login in a day or two
> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by johntdyer** [comment]
This happens to me constantly... really wish we could choose to run this w/o login

**Comment by carlvegfors** [comment]
I have the same problem. Works with Chrome but not Fully kiosk browser.
