### ISSUE TITLE
Failed to install addon, Unknown Error, see logs

### ISSUE THREAD

**Issue by redlegoman** [hassio-addons/addon-home-panel#48]
Just trying to install the add-on in hass.io (103.0) and I get:

"Failed to install addon, Unknown Error, see logs"

![image](https://user-images.githubusercontent.com/1895294/76350195-3a286900-6303-11ea-8d2a-1a756e39504f.png)

Which logs do I even look at? The /config/home-assistant.log has nothing.

**Comment by redlegoman** [comment]
Nevermind, I just kept doing it and eventually it worked. It'd be nice to know which logs I was supposed to look at though.

**Comment by sinclairpaul** [comment]
Failed add on installs will generally write errors to the Supervisor log.  The error itself isn't generated by the add on, but the Supervisor itself.
