### ISSUE TITLE
light switch can not control

### ISSUE THREAD

**Issue by czadikem** [hassio-addons/addon-home-panel#49]
# Problem/Motivation

> I cannot control my light switch with this ui

## Expected behavior

> when i push the light switch button it should turn on the light switch

## Actual behavior

> when i push the button it does nothing

**Comment by Modderhut** [comment]
I see the same, when controlling for example a hue light, color temperature and  brightness works as expected but I'm unable to turn the light on or off when clicking the light bulb icon.

**Comment by sinclairpaul** [comment]
You probably want to log this at https://github.com/timmo001/home-panel
