### ISSUE TITLE
Card type only shows "HASS" as an available type until saved and restarted, 

### ISSUE THREAD

**Issue by rpitera** [hassio-addons/addon-home-panel#5]
# Problem/Motivation
New cards don't show all available types

## Expected behavior

All available types should show when creating a new card

## Actual behavior

Only shows "Hass" until card is saved and panel is refreshed

## Steps to reproduce

1. Create new card.  Look at drop down for type.  Only Hass shows.
2. Put in minimal info for card and save.
3. When you get back to home panel screen, click on refresh button
4. Go back into edit and go to details for the card
5. Click on Type dropdown.  Now all options appear

**Comment by timmo001** [comment]
Please open this issue on the main repository:

https://github.com/timmo001/home-panel

Issues here are specifically for the addon, not the app itself. Thanks

**Comment by rpitera** [comment]
Sorry!
