### ISSUE TITLE
Addon_New Installation - Unable to change Theme color

### ISSUE THREAD

**Issue by quequi** [hassio-addons/addon-home-panel#52]
# Problem/Motivation

Unable to change default theme color. 

## Expected behavior

Change theme color in configuration section

## Actual behavior

Unable to change Default theme color

## Steps to reproduce

From Home assistant access to add-on from sidebar and in configuration try to change Theme color to other color. Theme color isn't changed.

## Proposed changes

Allow change Theme color.

System info and versions
=====================
 Add-on version: 1.7.2
 System: HassOS 3.13  (armv7 / raspberrypi3)
 Home Assistant Core: 0.109.2
 Home Assistant Supervisor: 220

**Comment by arripeo** [comment]
Also for me same problem, after some theme changes, the panel came back to the base theme without any chances to make changing.
My system is Hassio on HassOS 3.13 Supervisor 0.110.2 on raspberry PI4 4GB

**Comment by XeSSiV** [comment]
I'm getting this too. It worked initially but then stopped working. Inspecting when changes are made, I get these below. The Primary and Secondary colours were not set to lime at the time of the changes. I also am unable to change any other attributes under the Theme section. They give me the same errors as below.
Main.tsx:119 Uncaught TypeError: Cannot create property 'background_default' on string 'lime'
    at Object.B [as handleUpdateConfig] (Main.tsx:119)
    at Item.tsx:109
Main.tsx:119 Uncaught TypeError: Cannot create property 'background_paper' on string 'lime'
    at Object.B [as handleUpdateConfig] (Main.tsx:119)
    at Item.tsx:109

**Comment by timmo001** [comment]
This is the wrong repository for this issue. Please open your issue over at https://github.com/timmo001/home-panel if still relevant.

Make sure you use the provided templates and add as much detail as possible to your issue.

Thanks
