### ISSUE TITLE
Date and Time desappered after some changes

### ISSUE THREAD

**Issue by arripeo** [hassio-addons/addon-home-panel#53]
# Problem/Motivation
The date and time are no more present in any panel, I've chanced the size of time and anything seemed to be ok, when I've changed the date it disappeared and also the time hasn't been present. I've tried to replace the basic definition but date and time are still vanished
In community forum there are a lot of people with the same issue, more over it's impossible to change color and anything in the theme.

my system in Hassio on HassOS 3.13 with supervisor 0.110.2 on raspberry PI4 4GB

I've also noticed that the version of AddOn in my system is 1.7.3, meanwhile it seems exists a more recent version for other type of installation. it could be possible to upgrade the AddOn on Hassio with HassOS?
Thanks a lot

**Comment by timmo001** [comment]
This is the wrong repository for this issue. Please open your issue over at https://github.com/timmo001/home-panel if still relevant.

Make sure you use the provided templates and add as much detail as possible to your issue.

Thanks
