### ISSUE TITLE
Vaccum Cleaner card not working

### ISSUE THREAD

**Issue by arripeo** [hassio-addons/addon-home-panel#54]
# Problem/Motivation

I've created the card with the vacuum entity, the entity is found directly by the scrolling hints in the card editor, but it's impossible to have any command or status displayed. More over is not possible to change Icon or using icon from the system. The vacuum entity is referring to the Xiaomi Vacuum cleaner, on lovelace every thing works fine with it with different cards.

My system is Hassio on HassOS 3.13 Supervisor 0.110.2 on Raspberry PI4 4GB
Thanks

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by timmo001** [comment]
This is the wrong repository for this issue. Please open your issue over at https://github.com/timmo001/home-panel if still relevant.

Make sure you use the provided templates and add as much detail as possible to your issue.

Thanks
