### ISSUE TITLE
Unable to change theme under configuration

### ISSUE THREAD

**Issue by austino5308** [hassio-addons/addon-home-panel#55]
# Problem/Motivation
I am unable to save the Light / Dark theme or Change the Primary and Secondary color palette. 
When I change my Primary to any color and either go back to overview or refresh the page, the colors never saved and revert back to Pink / Pink as seen in the image below. 

I poked around in the config.db found under /data. I verified that pink / pink was in the database. I attempted to change the db file with the following:
"theme":{"type":"dark","primary":"grey","secondary":"red"

After a reboot of the docker container, my color was still Pink / Pink.

I even had this issue after a complete reinstall of Home Panel docker container. 

## Expected behavior
Color for Primary / Secondary to change and save.

## Actual behavior
Nothing happened, when refreshing the page it stayed on Pink / Pink.
![image](https://user-images.githubusercontent.com/18233106/82984799-da1b9780-9fc0-11ea-8c3b-9d5c5befb0c1.png)

## Steps to reproduce
Fresh install of home panel from HA Supervisor 
Running Home assistant / Home panel on Ubuntu 18.04 Server

**Comment by austino5308** [comment]
My apologies, I didn't see that there was an open issue for this already. I need some sleep. Are you able to merge this into issue #52

**Comment by timmo001** [comment]
This is the wrong repository for this issue. Please open your issue over at https://github.com/timmo001/home-panel if still relevant.

Make sure you use the provided templates and add as much detail as possible to your issue.

Thanks
