### ISSUE TITLE
Home Panel as a Hassio AddOn Gives "Can't connect" and won't allow settings chagnes

### ISSUE THREAD

**Issue by eldridgea** [hassio-addons/addon-home-panel#57]
# Problem/Motivation

> After login, I get "can't connect to 127.0.0.1:8123" error. r was able to create a Home Panel login, successfully, and when loading home panel I see the page UI for a brief moment, and then the frame shows the browser error "can't connect to 127.0.0.1:8123".

## Expected behavior

> Home Panel to load

## Actual behavior

> Browser error

## Steps to reproduce

> I'm not sure but what I *think* happened is I manually set the Home Panel's setting for Home Assistant's address as "127.0.0.1" in the Home Panel UI. I can't get into the UI to correct this and am unable to find anywhere that setting is stored elsewhere. Uninstalling and reinstalling in Supervisor doesn't appear to have an effect. 

## Proposed changes

> I'm not too sure, but maybe having a server option in the Configuration that I can edit would work? Or a way to completely purge all settings if that is actually persisting across reinstalls for some reason.

**Comment by timmo001** [comment]
Ah, so the url to use when you connect is the IP or hostname local to your client machine, not the server. Try clearing your cache/cookies and try again with the url you use to connect

**Comment by eldridgea** [comment]
🤦‍♂️ Yep, clearing cookies took care of it. Thank you so much! Love the software :-)
