### ISSUE TITLE
how to configure Home Panel

### ISSUE THREAD

**Issue by addboy58** [hassio-addons/addon-home-panel#58]
# how to configure Home Panel link not working

> could not get docs

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by mkotek** [comment]
Documentation has been moved over to here: [https://home-panel-docs.timmo.dev/issue-posting/](https://home-panel-docs.timmo.dev/issue-posting/)
