### ISSUE TITLE
Oops! Something went wrong.

### ISSUE THREAD

**Issue by mcampanha** [hassio-addons/addon-home-panel#6]
# Problem/Motivation

>  Oops! Something went wrong.
 
 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.

## Expected behavior

> open the web API

## Actual behavior

> doesn´t open

**Comment by tjorim** [comment]
Please make sure to include the whole log. Restart the add-on and refresh the logs until it stops. Then post it here in a code block.

**Comment by tjorim** [comment]
`[cont-init.d] 10-requirements.sh: executing...
FATAL: The configured certfile is not found`

You enabled SSL while the certificates don't exist or are in the wrong place. Check the readme for configuration options.
