### ISSUE TITLE
Home Panel - 401: Unauthorized

### ISSUE THREAD

**Issue by eadin79** [hassio-addons/addon-home-panel#60]
# Problem/Motivation
when open Home Panel require Home-assistant user and password.
I put the right user and pass and then gave me 401: Unauthorized

## Version used
 Home Panel Current version: 1.8.3 

## Expected behavior
 to open the Home Panel connected to Home Assistnant

## Actual behavior
401: Unauthorized

Any help how to solve it is welcomed!

**Comment by geekay1** [comment]
I'm having exactly the same issue. I'm a complete noob when it comes to Haas so any help is, as stated above, welcomed!

**Comment by eadin79** [comment]
You know the nice story? From my mobile Android it is working, from computer ...NOT AUTHORIZED

**Comment by dpeligro** [comment]
I have the same issue! Also noob in HA so no idea what to do :(
