### ISSUE TITLE
Saving theme fails

### ISSUE THREAD

**Issue by ylima-sa** [hassio-addons/addon-home-panel#61]
# Problem/Motivation

I just installed home panel and I tried to change background color, but for some reason I got an error:

```
Uncaught TypeError: Cannot create property 'background_default' on string 'indigo'
    at Object.z [as handleUpdateConfig] (Main.tsx:121)
    at Item.tsx:113

```
I am using Chrome on Windows.

Updating toggles, like "Dense Toolbar" works fine.

Very nice project :thumbsup:

**Comment by frenck** [comment]
This is an issue with Home Panel itself, not the add-on (that wraps it).

Please report your issue here: <https://github.com/timmo001/home-panel/issues>
