### ISSUE TITLE
Changing Configurations don't apply

### ISSUE THREAD

**Issue by dacool** [hassio-addons/addon-home-panel#65]
# Problem/Motivation

Changing Configuration settings don't apply or change.

When changing configuration settings,  it's seems that it appends data to the file in 
/usr/share/hassio/addons/data/a0d7b954_home-panel/config.db

And makes json file malfunction.

Running config.db file in jsonlint.com says:

Error: Parse error on line 48:
...t": 1609089488113} {	"config": {		"ge
----------------------^
Expecting 'EOF', '}', ',', ']', got '{'

## Expected behavior

When changing configurations settings, they change.

## Actual behavior

Configuration settings don't change.

## Steps to reproduce

Install version 1.8.3  Home panel.

**Comment by frenck** [comment]
Please report this issue upstream with Home Panel itself. Thanks 👍
