### ISSUE TITLE
Spinning wheel sign up

### ISSUE THREAD

**Issue by sanderlv** [hassio-addons/addon-home-panel#7]
I have hassio running with ssl let's encrypt. I do nut use duckdns. https://haas-ip works well (green lock). hassio is not connected from the internet (has internal to external access but nothing open from internet to. Completely runs locally.

I see in logging:
2019/01/24 07:39:02 [warn] 657#657: no resolver defined to resolve ocsp.int-x3.letsencrypt.org while requesting certificate status, responder: ocsp.int-x3.letsencrypt.org, certificate: "/ssl/fullchain.pem"

but not sure if this has to do with.

**Comment by timmo001** [comment]
Please clarify, what is the issue you are having? SSL? So long as you set the [certfile](https://github.com/hassio-addons/addon-home-panel#option-certfile) and [keyfile](https://github.com/hassio-addons/addon-home-panel#option-keyfile) to the same ones your HA works with, you should be fine

**Comment by sanderlv** [comment]
The files are there and set.

After opening "web UI"link I had to "register new account. But with no credentials that took the wheel spinning forever. Then I added a hass username and password and took me 1 step further... but then I get a very large url (anonymized) and the "server not found". I had to add the url manually (https://hass:8123 is used).

https://hass:8123/auth/authorize?response_type=code&client_id=https%3A%2F%2Fhass.%3A8234%2F&redirect_uri=https%3A%2F%2Fhass.%3A8234%2F%3Fauth_callback%3D1&state=eyJoYXNzVXJsIjoiaHR0cHM6Ly9oYXNzLnNhbmRlcmxlbGlldmVsZC5jb206ODEyMyIsImNsaWVudElkIjoiaHR0cHM6Ly9oYXNzLnNhbmRlcmxlbGlldmVsZC5ubDo4MjM0LyJ9

**Comment by timmo001** [comment]
I will merge this and the other issue opened into the upstream since they should hopefully be fixed when the API is rewritten.

https://github.com/timmo001/home-panel/issues/233
