### ISSUE TITLE
401: Unauthorized

### ISSUE THREAD

**Issue by vizion1988** [hassio-addons/addon-home-panel#86]
# Problem/Motivation

After installing the app I got the 401: Unauthorized error.

## Expected behavior

Home Panel and Home Assistant would couple, with use of Home Assistant user (Not an Administrator).

## Actual behavior

401: Unauthorized

## Steps to reproduce

Create new user in Home assistant. 
Install Home Panel via supervisor. 
Start Home Panel. 
Register new User. 
Connect to Home Assistant using the created user.

**Comment by Maharshi-Pathak** [comment]
Has there been any updates on this? I am having the same issue. Created new account for Home Panel by opening the Web UI via ingress. Tried to logging in to the Home Assistant but gives the 401: unauthorized. All other add-ons work, tried to open in Chrome, Firefox, and Edge but same result. Any help or guidance would be much appreciated @timmo001.
