### ISSUE TITLE
Adding Camera URL with parameter included doesn't work

### ISSUE THREAD

**Issue by ryanmboyce** [hassio-addons/addon-home-panel#9]
# Problem/Motivation

> Adding a widget type Camera that has a query string parameter already in the URL to load the image every 10 seconds breaks when the dashboard is loaded due to it appending an additional query string parameter (most likely to fetch up to date image?) 

Example URL: http://camera.url?api_key=ABCD123
On Home Panel load the request to get image is: http://camera.url?api_key=ABCD123?2156
which responds with 401 access denied due to additional parameter

## Expected behavior

> If parameter is already included in the URL use an ampersand & instead of ? question mark

## Actual behavior

> Adds second question mark to URL which breaks the original URL so camera image doesn't load

## Steps to reproduce

> Use camera that has a parameter in the URL to fetch still image

## Proposed changes

>Detect if camera URL has existing parameter and use ampersand instead of question mark?
Alternatively make the appending param behavior optional in UI

**Comment by timmo001** [comment]
This is an issue for the upstream repo. I have opened an issue for you here:

https://github.com/timmo001/home-panel/issues/209
